apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubehttpbin
  namespace: {{.Values.namespace}}
  labels:
    app: kubehttpbin
spec:
  replicas: {{.Values.numReplicas}}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: kubehttpbin
  template:
    metadata:
      labels:
        app: kubehttpbin
    spec:
      containers:
        - name: kubehttpbin
          image: quay.io/{{.Values.dockerOrg}}/kubehttpbin:{{.Values.dockerTag}}
          imagePullPolicy: {{.Values.dockerPullPolicy}}
          ports:
            - containerPort: {{.Values.containerPort}}
              name: http
          env:
            - name: "PORT"
              value: "{{.Values.containerPort}}"
          livenessProbe:
            httpGet:
              path: /get
              port: {{.Values.containerPort}}
            initialDelaySeconds: 30
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /get
              port: {{.Values.containerPort}}
            initialDelaySeconds: 30
            timeoutSeconds: 1
